language: rust
cache:
- bundler
- cargo

install: bundle

script:
# check that the advisory -> markdown render succeeds
- cargo run -p rustsec-website-gen
# check that jekyll can build the site
- jekyll build

branches:
  only:
    - master

rust:
  - stable

notifications:
  irc: 'irc.mozilla.org#rustsec'
